name: BaitersBurger Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Tests
        run: mvn -B clean test -Dspring.profiles.active=ci

  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build application package
        run: mvn -B package -DskipTests -Dspring.profiles.active=ci

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: baitersburger-customer-jar
          path: target/*.jar

  code-quality:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests with coverage
        run: mvn clean verify -Dspring.profiles.active=ci

      - name: Debug JaCoCo Report Location and Size
        run: |
            echo "Verificando se o jacoco.xml foi gerado em target/site/jacoco/"
            find target/ -name "jacoco.xml"
            
            if [ -f target/site/jacoco/jacoco.xml ]; then
              echo "Arquivo encontrado. Tamanho (linhas):"
              cat target/site/jacoco/jacoco.xml | wc -l
            else
              echo "ERRO: O arquivo jacoco.xml NÃO FOI ENCONTRADO no caminho esperado!"
              exit 1 # Falha o pipeline se o arquivo não estiver lá
            fi  

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Executando SonarCloud Scan para Pull Request..."
            mvn sonar:sonar \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=Leonardo Kegel \
              -Dsonar.projectKey=leonardokegel-baitersburger-customer \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.pullrequest.key=${{ github.event.number }} \
              -Dsonar.pullrequest.branch=${{ github.head_ref }} \
              -Dsonar.pullrequest.base=${{ github.base_ref }}
          else
            echo "Executando SonarCloud Scan para Branch Principal..."
            mvn sonar:sonar \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=Leonardo Kegel \
              -Dsonar.projectKey=leonardokegel-baitersburger-customer \
              -Dsonar.login=$SONAR_TOKEN
          fi
